### ISSUE TITLE
RefundReceipt is not a valid QBO Business Object

### ISSUE THREAD

**Issue by danyay** [sidecars/python-quickbooks#30] opened 2016-06-15 02:26 UTC
Hello,

Is RefundReceipt functional? I'm trying to create a simple RefundReceipt object and receiving the following traceback:

`Traceback (most recent call last):
  File "main.py", line 141, in <module>
    r.save()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/quickbooks/mixins.py", line 66, in save
    json_data = qb.create_object(self.qbo_object_name, self.to_json())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/quickbooks/client.py", line 215, in create_object
    self.isvalid_object_name(qbbo)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/quickbooks/client.py", line 230, in isvalid_object_name
    raise Exception("{0} is not a valid QBO Business Object.".format(object_name))
Exception: RefundReceipt is not a valid QBO Business Object.`

Doing the same with SalesReceipt is fully functional. Thank you!

**Comment by ej2** [comment] 2016-06-15 04:46
The issue is "RefundReceipt" is not listed in _BUSINESS_OBJECTS in client.py. I am working on an update to fix this issue and a few other things. I'll let you know when it is ready.

**Comment by ej2** [comment] 2016-06-16 03:14
This has been fixed in version 0.4.0.

**Closed by ej2** 2016-06-16 03:14 UTC

**Comment by danyay** [comment] 2016-06-16 17:03
Great, thank you!
